# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'setupWindow.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_SetupWindow(object):
    def setupUi(self, SetupWindow):
        SetupWindow.setObjectName(_fromUtf8("SetupWindow"))
        SetupWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        SetupWindow.resize(1080, 600)
        SetupWindow.setMinimumSize(QtCore.QSize(1080, 600))
        SetupWindow.setFocusPolicy(QtCore.Qt.NoFocus)
        self.centralwidget = QtGui.QWidget(SetupWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.ImagePreview = QtGui.QLabel(self.centralwidget)
        self.ImagePreview.setMinimumSize(QtCore.QSize(600, 400))
        self.ImagePreview.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.ImagePreview.setBaseSize(QtCore.QSize(600, 400))
        self.ImagePreview.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ImagePreview.setMouseTracking(True)
        self.ImagePreview.setFocusPolicy(QtCore.Qt.NoFocus)
        self.ImagePreview.setFrameShape(QtGui.QFrame.Box)
        self.ImagePreview.setFrameShadow(QtGui.QFrame.Plain)
        self.ImagePreview.setText(_fromUtf8(""))
        self.ImagePreview.setTextFormat(QtCore.Qt.AutoText)
        self.ImagePreview.setPixmap(QtGui.QPixmap(_fromUtf8("icons/ADDIXO.png")))
        self.ImagePreview.setScaledContents(True)
        self.ImagePreview.setAlignment(QtCore.Qt.AlignCenter)
        self.ImagePreview.setWordWrap(False)
        self.ImagePreview.setObjectName(_fromUtf8("ImagePreview"))
        self.verticalLayout.addWidget(self.ImagePreview)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.gridLayout.addLayout(self.horizontalLayout_3, 1, 0, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 2, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.saveMasterImageButton = QtGui.QPushButton(self.centralwidget)
        self.saveMasterImageButton.setEnabled(True)
        self.saveMasterImageButton.setObjectName(_fromUtf8("saveMasterImageButton"))
        self.horizontalLayout.addWidget(self.saveMasterImageButton)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.RetakeImageButton = QtGui.QPushButton(self.centralwidget)
        self.RetakeImageButton.setObjectName(_fromUtf8("RetakeImageButton"))
        self.horizontalLayout.addWidget(self.RetakeImageButton)
        self.SnapshotButton = QtGui.QPushButton(self.centralwidget)
        self.SnapshotButton.setObjectName(_fromUtf8("SnapshotButton"))
        self.horizontalLayout.addWidget(self.SnapshotButton)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.ToolsListSetup = QtGui.QGroupBox(self.centralwidget)
        self.ToolsListSetup.setEnabled(True)
        self.ToolsListSetup.setObjectName(_fromUtf8("ToolsListSetup"))
        self.ToolsList = QtGui.QVBoxLayout(self.ToolsListSetup)
        self.ToolsList.setObjectName(_fromUtf8("ToolsList"))
        self.Tool1 = QtGui.QHBoxLayout()
        self.Tool1.setObjectName(_fromUtf8("Tool1"))
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.ThreshSlider1 = QtGui.QSlider(self.ToolsListSetup)
        self.ThreshSlider1.setEnabled(False)
        self.ThreshSlider1.setMaximum(100)
        self.ThreshSlider1.setOrientation(QtCore.Qt.Horizontal)
        self.ThreshSlider1.setInvertedAppearance(False)
        self.ThreshSlider1.setInvertedControls(False)
        self.ThreshSlider1.setTickPosition(QtGui.QSlider.NoTicks)
        self.ThreshSlider1.setObjectName(_fromUtf8("ThreshSlider1"))
        self.gridLayout_6.addWidget(self.ThreshSlider1, 2, 0, 1, 1)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.ToolName1 = QtGui.QLabel(self.ToolsListSetup)
        self.ToolName1.setEnabled(False)
        self.ToolName1.setObjectName(_fromUtf8("ToolName1"))
        self.horizontalLayout_10.addWidget(self.ToolName1)
        self.ThreshValue1 = QtGui.QLabel(self.ToolsListSetup)
        self.ThreshValue1.setMaximumSize(QtCore.QSize(50, 50))
        self.ThreshValue1.setTextFormat(QtCore.Qt.PlainText)
        self.ThreshValue1.setScaledContents(False)
        self.ThreshValue1.setAlignment(QtCore.Qt.AlignCenter)
        self.ThreshValue1.setObjectName(_fromUtf8("ThreshValue1"))
        self.horizontalLayout_10.addWidget(self.ThreshValue1)
        self.gridLayout_6.addLayout(self.horizontalLayout_10, 1, 0, 1, 1)
        self.Tool1.addLayout(self.gridLayout_6)
        self.Enable1 = QtGui.QCheckBox(self.ToolsListSetup)
        self.Enable1.setEnabled(True)
        self.Enable1.setObjectName(_fromUtf8("Enable1"))
        self.Tool1.addWidget(self.Enable1)
        self.ToolSettings1 = QtGui.QToolButton(self.ToolsListSetup)
        self.ToolSettings1.setEnabled(False)
        self.ToolSettings1.setObjectName(_fromUtf8("ToolSettings1"))
        self.Tool1.addWidget(self.ToolSettings1)
        self.ToolsList.addLayout(self.Tool1)
        self.Tool2 = QtGui.QHBoxLayout()
        self.Tool2.setObjectName(_fromUtf8("Tool2"))
        self.gridLayout_9 = QtGui.QGridLayout()
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.ThreshSlider2 = QtGui.QSlider(self.ToolsListSetup)
        self.ThreshSlider2.setEnabled(False)
        self.ThreshSlider2.setMaximum(100)
        self.ThreshSlider2.setOrientation(QtCore.Qt.Horizontal)
        self.ThreshSlider2.setInvertedAppearance(False)
        self.ThreshSlider2.setInvertedControls(False)
        self.ThreshSlider2.setObjectName(_fromUtf8("ThreshSlider2"))
        self.gridLayout_9.addWidget(self.ThreshSlider2, 2, 0, 1, 1)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.ToolName2 = QtGui.QLabel(self.ToolsListSetup)
        self.ToolName2.setEnabled(False)
        self.ToolName2.setObjectName(_fromUtf8("ToolName2"))
        self.horizontalLayout_12.addWidget(self.ToolName2)
        self.ThreshValue2 = QtGui.QLabel(self.ToolsListSetup)
        self.ThreshValue2.setMaximumSize(QtCore.QSize(50, 50))
        self.ThreshValue2.setTextFormat(QtCore.Qt.PlainText)
        self.ThreshValue2.setScaledContents(False)
        self.ThreshValue2.setAlignment(QtCore.Qt.AlignCenter)
        self.ThreshValue2.setObjectName(_fromUtf8("ThreshValue2"))
        self.horizontalLayout_12.addWidget(self.ThreshValue2)
        self.gridLayout_9.addLayout(self.horizontalLayout_12, 1, 0, 1, 1)
        self.Tool2.addLayout(self.gridLayout_9)
        self.Enable2 = QtGui.QCheckBox(self.ToolsListSetup)
        self.Enable2.setObjectName(_fromUtf8("Enable2"))
        self.Tool2.addWidget(self.Enable2)
        self.ToolSettings2 = QtGui.QToolButton(self.ToolsListSetup)
        self.ToolSettings2.setEnabled(False)
        self.ToolSettings2.setObjectName(_fromUtf8("ToolSettings2"))
        self.Tool2.addWidget(self.ToolSettings2)
        self.ToolsList.addLayout(self.Tool2)
        self.Tool3 = QtGui.QHBoxLayout()
        self.Tool3.setObjectName(_fromUtf8("Tool3"))
        self.gridLayout_8 = QtGui.QGridLayout()
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.ThreshSlider3 = QtGui.QSlider(self.ToolsListSetup)
        self.ThreshSlider3.setEnabled(False)
        self.ThreshSlider3.setMaximum(100)
        self.ThreshSlider3.setOrientation(QtCore.Qt.Horizontal)
        self.ThreshSlider3.setInvertedAppearance(False)
        self.ThreshSlider3.setInvertedControls(False)
        self.ThreshSlider3.setObjectName(_fromUtf8("ThreshSlider3"))
        self.gridLayout_8.addWidget(self.ThreshSlider3, 2, 0, 1, 1)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.ToolName3 = QtGui.QLabel(self.ToolsListSetup)
        self.ToolName3.setEnabled(False)
        self.ToolName3.setObjectName(_fromUtf8("ToolName3"))
        self.horizontalLayout_11.addWidget(self.ToolName3)
        self.ThreshValue3 = QtGui.QLabel(self.ToolsListSetup)
        self.ThreshValue3.setMaximumSize(QtCore.QSize(50, 50))
        self.ThreshValue3.setTextFormat(QtCore.Qt.PlainText)
        self.ThreshValue3.setScaledContents(False)
        self.ThreshValue3.setAlignment(QtCore.Qt.AlignCenter)
        self.ThreshValue3.setObjectName(_fromUtf8("ThreshValue3"))
        self.horizontalLayout_11.addWidget(self.ThreshValue3)
        self.gridLayout_8.addLayout(self.horizontalLayout_11, 1, 0, 1, 1)
        self.Tool3.addLayout(self.gridLayout_8)
        self.Enable3 = QtGui.QCheckBox(self.ToolsListSetup)
        self.Enable3.setObjectName(_fromUtf8("Enable3"))
        self.Tool3.addWidget(self.Enable3)
        self.ToolSettings3 = QtGui.QToolButton(self.ToolsListSetup)
        self.ToolSettings3.setEnabled(False)
        self.ToolSettings3.setObjectName(_fromUtf8("ToolSettings3"))
        self.Tool3.addWidget(self.ToolSettings3)
        self.ToolsList.addLayout(self.Tool3)
        self.Tool4 = QtGui.QHBoxLayout()
        self.Tool4.setObjectName(_fromUtf8("Tool4"))
        self.gridLayout_10 = QtGui.QGridLayout()
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.ThreshSlider4 = QtGui.QSlider(self.ToolsListSetup)
        self.ThreshSlider4.setEnabled(False)
        self.ThreshSlider4.setMaximum(100)
        self.ThreshSlider4.setOrientation(QtCore.Qt.Horizontal)
        self.ThreshSlider4.setInvertedAppearance(False)
        self.ThreshSlider4.setInvertedControls(False)
        self.ThreshSlider4.setObjectName(_fromUtf8("ThreshSlider4"))
        self.gridLayout_10.addWidget(self.ThreshSlider4, 2, 0, 1, 1)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.ToolName4 = QtGui.QLabel(self.ToolsListSetup)
        self.ToolName4.setEnabled(False)
        self.ToolName4.setObjectName(_fromUtf8("ToolName4"))
        self.horizontalLayout_13.addWidget(self.ToolName4)
        self.ThreshValue4 = QtGui.QLabel(self.ToolsListSetup)
        self.ThreshValue4.setMaximumSize(QtCore.QSize(50, 50))
        self.ThreshValue4.setTextFormat(QtCore.Qt.PlainText)
        self.ThreshValue4.setScaledContents(False)
        self.ThreshValue4.setAlignment(QtCore.Qt.AlignCenter)
        self.ThreshValue4.setObjectName(_fromUtf8("ThreshValue4"))
        self.horizontalLayout_13.addWidget(self.ThreshValue4)
        self.gridLayout_10.addLayout(self.horizontalLayout_13, 1, 0, 1, 1)
        self.Tool4.addLayout(self.gridLayout_10)
        self.Enable4 = QtGui.QCheckBox(self.ToolsListSetup)
        self.Enable4.setObjectName(_fromUtf8("Enable4"))
        self.Tool4.addWidget(self.Enable4)
        self.ToolSettings4 = QtGui.QToolButton(self.ToolsListSetup)
        self.ToolSettings4.setEnabled(False)
        self.ToolSettings4.setObjectName(_fromUtf8("ToolSettings4"))
        self.Tool4.addWidget(self.ToolSettings4)
        self.ToolsList.addLayout(self.Tool4)
        self.gridLayout.addWidget(self.ToolsListSetup, 0, 1, 2, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem5)
        self.PreviousStepButton = QtGui.QPushButton(self.centralwidget)
        self.PreviousStepButton.setMinimumSize(QtCore.QSize(100, 0))
        self.PreviousStepButton.setObjectName(_fromUtf8("PreviousStepButton"))
        self.verticalLayout_4.addWidget(self.PreviousStepButton)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem6)
        self.NextStepButton = QtGui.QPushButton(self.centralwidget)
        self.NextStepButton.setMinimumSize(QtCore.QSize(100, 0))
        self.NextStepButton.setObjectName(_fromUtf8("NextStepButton"))
        self.verticalLayout_3.addWidget(self.NextStepButton)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem7)
        self.gridLayout.addLayout(self.horizontalLayout_2, 2, 1, 1, 1)
        SetupWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(SetupWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1080, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        SetupWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(SetupWindow)
        self.statusbar.setEnabled(True)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        SetupWindow.setStatusBar(self.statusbar)

        self.retranslateUi(SetupWindow)
        QtCore.QObject.connect(self.SnapshotButton, QtCore.SIGNAL(_fromUtf8("clicked()")), SetupWindow.snapshot)
        QtCore.QObject.connect(self.saveMasterImageButton, QtCore.SIGNAL(_fromUtf8("clicked()")), SetupWindow.saveMasterFrame)
        QtCore.QObject.connect(self.RetakeImageButton, QtCore.SIGNAL(_fromUtf8("clicked()")), SetupWindow.liveStream)
        QtCore.QObject.connect(self.ThreshSlider2, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.ThreshValue2.setNum)
        QtCore.QObject.connect(self.ThreshSlider3, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.ThreshValue3.setNum)
        QtCore.QObject.connect(self.ThreshSlider4, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.ThreshValue4.setNum)
        QtCore.QObject.connect(self.Enable2, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.ToolSettings2.setEnabled)
        QtCore.QObject.connect(self.Enable2, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.ThreshSlider2.setEnabled)
        QtCore.QObject.connect(self.Enable2, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.ToolName2.setEnabled)
        QtCore.QObject.connect(self.Enable3, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.ToolSettings3.setEnabled)
        QtCore.QObject.connect(self.Enable3, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.ThreshSlider3.setEnabled)
        QtCore.QObject.connect(self.Enable3, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.ToolName3.setEnabled)
        QtCore.QObject.connect(self.Enable4, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.ToolSettings4.setEnabled)
        QtCore.QObject.connect(self.Enable4, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.ThreshSlider4.setEnabled)
        QtCore.QObject.connect(self.Enable4, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.ToolName4.setEnabled)
        QtCore.QObject.connect(self.ToolSettings2, QtCore.SIGNAL(_fromUtf8("clicked()")), SetupWindow.showToolSettings2)
        QtCore.QObject.connect(self.ToolSettings3, QtCore.SIGNAL(_fromUtf8("clicked()")), SetupWindow.showToolSettings3)
        QtCore.QObject.connect(self.ToolSettings4, QtCore.SIGNAL(_fromUtf8("clicked()")), SetupWindow.showToolSettings4)
        QtCore.QObject.connect(self.Enable1, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.ToolSettings1.setEnabled)
        QtCore.QObject.connect(self.Enable1, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.ToolName1.setEnabled)
        QtCore.QObject.connect(self.Enable1, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.ThreshSlider1.setEnabled)
        QtCore.QObject.connect(self.ToolSettings1, QtCore.SIGNAL(_fromUtf8("clicked()")), SetupWindow.showToolSettings1)
        QtCore.QObject.connect(self.ThreshSlider1, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.ThreshValue1.setNum)
        QtCore.QObject.connect(self.NextStepButton, QtCore.SIGNAL(_fromUtf8("clicked()")), SetupWindow.nextPressedOnce)
        QtCore.QObject.connect(self.PreviousStepButton, QtCore.SIGNAL(_fromUtf8("clicked()")), SetupWindow.close)
        QtCore.QMetaObject.connectSlotsByName(SetupWindow)

    def retranslateUi(self, SetupWindow):
        SetupWindow.setWindowTitle(_translate("SetupWindow", "Setup", None))
        self.saveMasterImageButton.setText(_translate("SetupWindow", "Save Master Image", None))
        self.RetakeImageButton.setText(_translate("SetupWindow", "Retake Image", None))
        self.SnapshotButton.setText(_translate("SetupWindow", "snapshot Image", None))
        self.ToolName1.setText(_translate("SetupWindow", "Tool 1", None))
        self.ThreshValue1.setText(_translate("SetupWindow", "0", None))
        self.Enable1.setText(_translate("SetupWindow", "Enable", None))
        self.ToolSettings1.setText(_translate("SetupWindow", "...", None))
        self.ToolName2.setText(_translate("SetupWindow", "Tool 2 ", None))
        self.ThreshValue2.setText(_translate("SetupWindow", "0", None))
        self.Enable2.setText(_translate("SetupWindow", "Enable", None))
        self.ToolSettings2.setText(_translate("SetupWindow", "...", None))
        self.ToolName3.setText(_translate("SetupWindow", "Tool 3 ", None))
        self.ThreshValue3.setText(_translate("SetupWindow", "0", None))
        self.Enable3.setText(_translate("SetupWindow", "Enable", None))
        self.ToolSettings3.setText(_translate("SetupWindow", "...", None))
        self.ToolName4.setText(_translate("SetupWindow", "Tool 4 ", None))
        self.ThreshValue4.setText(_translate("SetupWindow", "0", None))
        self.Enable4.setText(_translate("SetupWindow", "Enable", None))
        self.ToolSettings4.setText(_translate("SetupWindow", "...", None))
        self.PreviousStepButton.setText(_translate("SetupWindow", "previous step", None))
        self.NextStepButton.setText(_translate("SetupWindow", "Next Step", None))

